# Generated by Django 4.1.6 on 2023-02-02 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "owner",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Creado por:",
                    ),
                ),
                (
                    "update_by",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Actualizado por:",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creación del Registro:"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Modificación del Registro:"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Nombre de la moneda"
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        max_length=10, verbose_name="Símbolo de la moneda"
                    ),
                ),
            ],
            options={
                "verbose_name": "Moneda",
                "verbose_name_plural": "Monedas",
            },
        ),
        migrations.CreateModel(
            name="Statistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "owner",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Creado por:",
                    ),
                ),
                (
                    "update_by",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Actualizado por:",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creación del Registro:"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Modificación del Registro:"
                    ),
                ),
                ("price", models.CharField(max_length=50, verbose_name="Precio")),
                (
                    "low_high_24h",
                    models.CharField(max_length=50, verbose_name="Bajo y alto en 24h"),
                ),
                (
                    "trading_volume_24h",
                    models.CharField(
                        max_length=50, verbose_name="Volumen de comercio en 24h"
                    ),
                ),
                (
                    "market_cap",
                    models.CharField(
                        max_length=50, verbose_name="Capitalización de mercado"
                    ),
                ),
                (
                    "market_dominance",
                    models.CharField(max_length=50, verbose_name="Dominio de mercado"),
                ),
                (
                    "market_rank",
                    models.CharField(max_length=50, verbose_name="Rango de mercado"),
                ),
                (
                    "circulating_supply",
                    models.CharField(
                        max_length=50, verbose_name="Suministro circulante"
                    ),
                ),
                (
                    "total_supply",
                    models.CharField(max_length=50, verbose_name="Suministro total"),
                ),
                (
                    "max_supply",
                    models.CharField(max_length=50, verbose_name="Suministro máximo"),
                ),
                (
                    "coin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exchange.coin",
                        verbose_name="Moneda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estadística",
                "verbose_name_plural": "Estadísticas",
            },
        ),
    ]
